version: '2'

services:
  db:
    restart: always
    container_name: mongodb_server
    image: ivanmarban/armhf-mongodb
    volumes:
      - ./leanote_data:/var/lib/mongodb
  
  maildev:
    image: kroschu/armhf-maildev
    container_name: leanote_maildev
    command: env NODE_ENV=development bin/maildev --web 80 --smtp 25 --outgoing-host  smtp.gmail.com  --outgoing-secure  true --outgoing-port 465  --outgoing-user 'tukroschu@gmail.com'  --outgoing-pass 'Agni05230523' --auto-relay trebatk@hotmail.com --verbose
    ports:
    - 8080:80
    environment:
      - NODE_ENV=development

  server:
    image: kroschu/armhf-leanote
    environment:
      - SITE_URL="https://blog.uabp.ml"
    depends_on:
      - db
      - maildev
    restart: always
    ports:
      - 9004:9000
    links:
      - db:mongodb
      - maildev:maildev
    container_name: leanote_server

    volumes:
      - ./leanote/data:/leanote/data

