version: '2'

services:
  db:
    restart: always
    container_name: mongodb_server
    image: ivanmarban/armhf-mongodb
    volumes:
      - ./leanote_data:/var/lib/mongodb
  
  
  server:
    image: kroschu/armhf-leanote
    environment:
      - SITE_URL="https://blog.uabp.ml

