version: '2'

services:
  db:
    restart: always
    container_name: mongodb_server
    image: ivanmarban/armhf-mongodb
    volumes:
      - ./leanote_data:/var/lib/mongodb

  server:
    image: kroschu/armhf-leanote
    environment:
      - SITE_URL="http://localhost:9004"
    depends_on:
      - db
    restart: always
    ports:
      - 9004:9000
    links:
      - db:mongodb
    container_name: leanote_server

    volumes:
      - ./leanote/data:/leanote/data
